server:
  port: 8084

spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/ #当前zuul网关想要注册到哪个注册中心这里注册到之前搭的9000上。

#路由规则定义。这里定义两种路由规则route1和route2
#，代表访问网关/test01/**或/test02/**时。
#路由到服务名为 eurekaservice1或 eureka
#service2中的服务集群去。
zuul:
  routes:
    route1:
      path: /Controller/**
      serviceId: eurekaservice1
    route2:
      path: /test02/**
      serviceId: eurekaservice2